// Automatically generated by Opus v0.30
namespace glRap
{
    // Define module classes here
    class glrap : C.DynamicLibrary
    {
        sealed class SourceFiles : C.ObjectFileCollection
        {
            public SourceFiles()
            {
                this.AddRelativePaths(this, "source", "unix", "entrypoint.cpp");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles sourceFiles = new SourceFiles();
    }
}
